# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.16.3
    build:
      context: .
      args:
        GROUPID: 1000
        GROUPNAME: adeleo
        USERID: 1000
        USERNAME: adeleo
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
